import os

import tweepy

BULBEA_TWITTER_API_KEY             = os.getenv('BULBEA_TWITTER_API_KEY')
BULBEA_TWITTER_API_SECRET          = os.getenv('BULBEA_TWITTER_API_SECRET')
BULBEA_TWITTER_ACCESS_TOKEN        = os.getenv('BULBEA_TWITTER_ACCESS_TOKEN')
BULBEA_TWITTER_ACCESS_TOKEN_SECRET = os.getenv('BULBEA_TWITTER_ACCESS_TOKEN_SECRET')

auth = tweepy.OAuthHandler(BULBEA_TWITTER_API_KEY, BULBEA_TWITTER_API_SECRET)
auth.set_access_token(BULBEA_TWITTER_ACCESS_TOKEN, BULBEA_TWITTER_ACCESS_TOKEN_SECRET)

API  = tweepy.API(auth)
