#!/usr/bin/env python

import sys
import os

sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('_themes'))

import package
import bulbea as bb

project              = package.name
version              = package.version
release              = package.release
html_theme           = 'alabaster'
html_theme_options   = {
    'github_user'       : package.github_username,
    'github_repo'       : package.github_repository,
    'github_banner'     : True,
    'show_powered_by'   : False,
    'show_related'      : False,
}
html_show_sourcelink = False
html_static_path     = ['_static']
html_sidebars        = {
    '**': ['sidebar-logo.html']
}
pygments_style       = 'flask_theme_support.FlaskyStyle'
extensions           = [
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax'
]
source_suffix        = '.rst'
master_doc           = 'index'
templates_path       = ['_templates']
exclude_patterns     = ['_build']














copyright = '2017, Achilles Rasquinha'
author = 'Achilles Rasquinha'
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None


# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False
